version: "3.0"

services:
  steuerrecht:
    build: ./
    # gunicorn project_finance.wsgi:application -w 4 --bind 0.0.0.0:8000 
    command: python3 -m flask run --host=0.0.0.0 --port=8000
    #expose:
    #  - 8000
    ports:
      - 8000:8000
    container_name: steuerrecht
    volumes:
      - ./recht:/app/recht
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    container_name: reverse-proxy
    labels:
      kompose.service.type: LoadBalancer
